title: Uploading Fucking Code...
markdown: kramdown
url: "https://yj76461.github.io"
baseurl: ""

analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "UA-235338320-1"
    anonymize_ip         : # true, false (default)
# for atom feed
author: 
  name: YJ
  email: ifyoucomeback@kakao.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]

